---
production:
  services:
    registry:
      uri: "http://registry:80/api/"
      apiVersion: v1
  port: 80
  logger: 'info'
development:
  services:
    registry:
      uri: "http://localhost:8081/api/"
      apiVersion: v1
  port: 5030
  logger: 'debug'
